### ISSUE TITLE
Free space for rootfs on common graph (graphs for filesystem)

### ISSUE THREAD

**Issue by kostin** [danschultzer/monit-graph#1]
Thank you for nice tool. Is there some plans for add filesystem graphs? Not only processes.

For example Monit shows blocks free total and inodes free in percents (if `check device rootfs with path /` in config) and it can be show on common graph for server.

**Comment by danschultzer** [comment]
Thanks @kostin. I've no plans to add in filesystem graphs, but it should be simple enough. Feel free to fork and send me a PR.
