### ISSUE TITLE
Does not recognise service ( type=7, program )

### ISSUE THREAD

**Issue by Marqin** [danschultzer/monit-graph#2]
@danschultzer 

My Monit version is 5.14 and monit-graph does not recognise service HDDtemp.
Service is properly displayed on monit webpanel and appears in xml file ( as `<service type="7">
` , but is ignored by monit-graph.
Service code:

```
check program HDDtemp with path "/root/temp_test.sh"
    if status > 45 then alert
    group temperature
```

**Comment by Marqin** [comment]
On the other hand I have services two services ( in xml as `<service type="3">` ) that are working properly with monit-graph. Here is their code:

```
check process nginx with pidfile /run/nginx.pid
check process php-fpm with pidfile /run/php-fpm/php-fpm.pid
```

**Comment by danschultzer** [comment]
You'll need to add logic to handle type 7. Right now [only type 3 and 5 are handled](https://github.com/danschultzer/monit-graph/blob/master/monit-graph.class.php#L241). Each service type may have very different key/value metrics, so only the most common types are handled. Feel free to open a PR.
