### ISSUE TITLE
Weird, sudden poll time issue

### ISSUE THREAD

**Issue by pentago** [danschultzer/monit-graph#6]
Couple of days ago I started receiving this email:

> Message 14490:
> From root@example.com  Sat Oct  8 13:42:40 2016
> X-Original-To: root
> Delivered-To: root@example.com
> From: root@example.com (Cron Daemon)
> To: root@example.com
> Subject: Cron root@example /usr/local/bin/php /home/user/status.example.com/cron.php >> /var/log/monit-graph.log
> X-Cron-Env: <SHELL=/bin/sh>
> X-Cron-Env: <PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin>
> X-Cron-Env: <HOME=/root>
> X-Cron-Env: <LOGNAME=root>
> X-Cron-Env: <USER=root>
> Date: Sat,  8 Oct 2016 13:42:40 +0200 (CEST)
> 
> [MonitGraph] /usr/home/user/status.example.com/monit-graph.class.php line 108: Poll time has not been reached (missing 167538 seconds), waiting for one more cycle

Stats collection doesn't work.
Any suggestion on what might be the issue?

Thanks

**Comment by danschultzer** [comment]
Sorry for not answering, haven't been maintaining this library for a while. I've revamped the whole codebase, please try it out.
