### ISSUE TITLE
SSL errors on monit 5.20

### ISSUE THREAD

**Issue by yrpen** [danschultzer/monit-graph#9]
`php /home/graph/web/cron.php`

`[MonitGraph] /home/graph/monit-graph/web/monit-graph.class.php line 154: cURL Error (35): error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure`

Commenting out lines:
> curl_setopt($ch, CURLOPT_SSLVERSION, 3);
> if($verify_ssl) curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
> else curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);

and add line:
> curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);

Fixed problem. At this moment, I think ssl version should be configurable per connection and default should be TLS 1.0 or 1.1, not SSL v3.

Thanks for this software :+1:

**Comment by danschultzer** [comment]
Thanks! I've removed `CURLOPT_SSLVERSION` option entirely, so the default is used instead (not to mention SSL v3 is horribly outdated and vulnerable).

You can set the `verify_ssl` to false to prevent it from checking:

```ini
[0]
name                    = "localhost"
server_id               = 1
config[url]             = "localhost:2812"
config[ssl]             = true
config[http_username]   = "admin"
config[http_password]   = "monit"
config[verify_ssl] = true
```

Heads up: I'll probably rename this value in the future, planning to get a full rewrite done as soon as I've the time!
